apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-backend-service-configmap
  namespace: dev
data:
  DEBUG: "True"
  DB_HOST: root
  DB_NAME: task_manager
  DB_PORT: "3306"
  ALLOWED_HOSTS: "localhost,127.0.0.1,54.254.120.73"
  CORS_ALLOWED_ORIGINS: http://13.213.19.86:5173
  RESEND_FROM_EMAIL: "no-reply@mysitedesign.site"
